remove html file from repo and formatting
HumanCellAtlas/falcon pull request #43
Opened 2020-03-10 19:17 UTC by Fab-T

### Purpose

- No issue is linked to this PR.

### Changes

- No changes.

### Review Instructions

- No instructions.

2020-03-10 19:32 UTC, rexwangcc requested changes
Thanks for fixing it! I left my 2 cents.

2020-03-10 19:32 UTC, rexwangcc commented on falcon/queue_handler.py
> +            if settings.docRootPath:
optional: this could also be done by `papthlib` with `parents=True, exist_ok=True`, see https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir

2020-03-10 19:32 UTC, rexwangcc commented on falcon/queue_handler.py
> +            f = open(filename, "w")
use `with open()` instead of open() to avoid unhandled file connections

2020-03-10 22:50 UTC, rexwangcc approved these changes
I have one extra comment and otherwise LGTM!

2020-03-10 22:50 UTC, rexwangcc commented on falcon/queue_handler.py
> +                f.close()
no need to close within the `with` context manager; see [here](https://www.geeksforgeeks.org/context-manager-in-python/)

2020-03-11 12:13 UTC, Fab-T commented on falcon/queue_handler.py
> +                f.close()
indeed , thanks for the ref

2020-03-11 12:20 UTC, rexwangcc approved these changes

2020-03-11 13:35 UTC, merged